include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: false  # Allowed for this MVP
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    always_use_package_imports: false
